################################################################################
# Playbook example that performs some simple operations on a remote mvs system
################################################################################

---
- name: "MVS Playbook demo mvs.yaml"
  hosts: mvs
  environment:
    _BPXK_AUTOCVT: '{{ _BPXK_AUTOCVT }}'        
    PYTHON_DIR_NAME: '{{ PYTHON_DIR_NAME }}'      
    INSTALL: '{{ INSTALL }}'              
    RELEASE_NAME: '{{ RELEASE_NAME }}'         
    RELEASE_TYPE: '{{ RELEASE_TYPE }}'         
    RELEASE_DIR: '{{ RELEASE_DIR }}'          
    PYTHON_ENV: '{{ PYTHON_ENV }}'           
    PYTHON_HOME: '{{ PYTHON_HOME }}'          
    PATH: '{{ PATH }}'                 
    LIBPATH: '{{ LIBPATH }}'              
    FFI_LIB: '{{ FFI_LIB }}'              
    TERMINFO: '{{ TERMINFO }}'             
    PKG_CONFIG_PATH: '{{ PKG_CONFIG_PATH }}'      
    CURL_CA_BUNDLE: '{{ CURL_CA_BUNDLE }}' 
    
  tasks:
  - name: "Print name of current/working directory."
    command: pwd 
    register: out
    
  - debug: var=out.stdout_lines
  
  - name: "Print the current/working directories files."
    command: ls -la 
    register: out
    
  - debug: var=out.stdout_lines
  
  - name: "Make the directory /tmp/rbac-demo"
    file: 
      path: "/tmp/rbac-demo/"
      state: directory
    
  - debug: var=out.stdout_lines
  
  - name: "List directory in /tmp"
    command: ls -la /tmp
    register: out
    
  - debug: var=out.stdout_lines
  
  - name: "Delete directory /tmp/rbac-demo"
    file: 
      path: "/tmp/rbac-demo/"
      state: absent
      
